#ifndef BCM2711_H
#define BCM2711_H

#define ARM_IO_BASE		0xFE000000
#define ARM_IO_END		(ARM_IO_BASE + 0xFFFFFF)


#define GPU_IO_BASE		0x7E000000

#define GPU_CACHED_BASE		0x40000000
#define GPU_UNCACHED_BASE	0xC0000000


//
// General Purpose I/O
//
#define ARM_GPIO_BASE    (ARM_IO_BASE + 0x200000)

#define ARM_GPIO_GPFSEL0 (ARM_GPIO_BASE + 0x00)
#define ARM_GPIO_GPFSEL1 (ARM_GPIO_BASE + 0x04)
#define ARM_GPIO_GPFSEL2 (ARM_GPIO_BASE + 0x08)
#define ARM_GPIO_GPFSEL3 (ARM_GPIO_BASE + 0x0c)
#define ARM_GPIO_GPFSEL4 (ARM_GPIO_BASE + 0x10)
#define ARM_GPIO_GPFSEL5 (ARM_GPIO_BASE + 0x14)
#define ARM_GPIO_GPSET0 (ARM_GPIO_BASE + 0x1c)
#define ARM_GPIO_GPSET1 (ARM_GPIO_BASE + 0x20)
#define ARM_GPIO_GPCLR0 (ARM_GPIO_BASE + 0x28)
#define ARM_GPIO_GPCLR1 (ARM_GPIO_BASE + 0x2c)
#define ARM_GPIO_GPLEV0 (ARM_GPIO_BASE + 0x34)
#define ARM_GPIO_GPLEV1 (ARM_GPIO_BASE + 0x38)
#define ARM_GPIO_GPEDS0 (ARM_GPIO_BASE + 0x40)
#define ARM_GPIO_GPEDS1 (ARM_GPIO_BASE + 0x44)
#define ARM_GPIO_GPREN0 (ARM_GPIO_BASE + 0x4c)
#define ARM_GPIO_GPREN1 (ARM_GPIO_BASE + 0x50)
#define ARM_GPIO_GPFEN0 (ARM_GPIO_BASE + 0x58)
#define ARM_GPIO_GPFEN1 (ARM_GPIO_BASE + 0x5c)
#define ARM_GPIO_GPFHEN0 (ARM_GPIO_BASE + 0x64)
#define ARM_GPIO_GPHEN1 (ARM_GPIO_BASE + 0x68)
#define ARM_GPIO_GPLEN0 (ARM_GPIO_BASE + 0x70)
#define ARM_GPIO_GPLEN1 (ARM_GPIO_BASE + 0x74)
#define ARM_GPIO_GPAREN0 (ARM_GPIO_BASE + 0x7c)
#define ARM_GPIO_GPAREN1 (ARM_GPIO_BASE + 0x80)
#define ARM_GPIO_GPAFEN0 (ARM_GPIO_BASE + 0x88)
#define ARM_GPIO_GPAFEN1 (ARM_GPIO_BASE + 0x8c)
#define ARM_GPIO_GPIO_PUPDNN0 (ARM_GPIO_BASE + 0xe4)
#define ARM_GPIO_GPIO_PUPDNN1 (ARM_GPIO_BASE + 0xe8)
#define ARM_GPIO_GPIO_PUPDNN2 (ARM_GPIO_BASE + 0xec)
#define ARM_GPIO_GPIO_PUPDNN3 (ARM_GPIO_BASE + 0xf0)


//
//  Auxilaries
//  UART1, SP1, SP2
//

#define ARM_AUX_BASE (ARM_IO_BASE + 0x215000)
#define ARM_AUX_IRQ (ARM_AUX_BASE + 0x00)
#define ARM_AUX_ENABLES (ARM_AUX_BASE + 0x04)
#define ARM_AUX_MU_IO_REG (ARM_AUX_BASE + 0x40)
#define ARM_AUX_MU_IER_REG (ARM_AUX_BASE + 0x44)
#define ARM_AUX_MU_IIR_REG (ARM_AUX_BASE + 0x48)
#define ARM_AUX_MU_LCR_REG (ARM_AUX_BASE + 0x4c)
#define ARM_AUX_MU_MCR_REG (ARM_AUX_BASE + 0x50)
#define ARM_AUX_MU_LSR_REG (ARM_AUX_BASE + 0x54)
#define ARM_AUX_MU_MSR_REG (ARM_AUX_BASE + 0x58)
#define ARM_AUX_MU_SCRATCH (ARM_AUX_BASE + 0x5c)
#define ARM_AUX_MU_CNTL_REG (ARM_AUX_BASE + 0x60)
#define ARM_AUX_MU_STAT_REG (ARM_AUX_BASE + 0x64)
#define ARM_AUX_MU_BAUD_REG (ARM_AUX_BASE + 0x68)
#define ARM_AUX_SPI1_CNTL0_REGSP (ARM_AUX_BASE + 0x80)
#define ARM_AUX_SPI1_CNTL1_REGSP (ARM_AUX_BASE + 0x84)
#define ARM_AUX_SPI1_STAT_REGSP (ARM_AUX_BASE + 0x88)
#define ARM_AUX_SPI1_PEEK_REGSP (ARM_AUX_BASE + 0x8c)
#define ARM_AUX_SPI1_IO_REa (ARM_AUX_BASE + 0xa0)
#define ARM_AUX_SPI1_IO_REb (ARM_AUX_BASE + 0xa4)
#define ARM_AUX_SPI1_IO_REc (ARM_AUX_BASE + 0xa8)
#define ARM_AUX_SPI1_IO_REd (ARM_AUX_BASE + 0xac)
#define ARM_AUX_SPI1_TXHOLD_REa (ARM_AUX_BASE + 0xb0)
#define ARM_AUX_SPI1_TXHOLD_REb (ARM_AUX_BASE + 0xb4)
#define ARM_AUX_SPI1_TXHOLD_REc (ARM_AUX_BASE + 0xb8)
#define ARM_AUX_SPI1_TXHOLD_REd (ARM_AUX_BASE + 0xbc)
#define ARM_AUX_SPI2_CNTL0_REGSP (ARM_AUX_BASE + 0xc0)
#define ARM_AUX_SPI2_CNTL1_REGSP (ARM_AUX_BASE + 0xc4)
#define ARM_AUX_SPI2_STAT_REGSP (ARM_AUX_BASE + 0xc8)
#define ARM_AUX_SPI2_PEEK_REGSP (ARM_AUX_BASE + 0xcc)
#define ARM_AUX_SPI2_IO_REa (ARM_AUX_BASE + 0xe0)
#define ARM_AUX_SPI2_IO_REb (ARM_AUX_BASE + 0xe4)
#define ARM_AUX_SPI2_IO_REc (ARM_AUX_BASE + 0xe8)
#define ARM_AUX_SPI2_IO_REd (ARM_AUX_BASE + 0xec)
#define ARM_AUX_SPI2_TXHOLD_REa (ARM_AUX_BASE + 0xf0)
#define ARM_AUX_SPI2_TXHOLD_REb (ARM_AUX_BASE + 0xf4)
#define ARM_AUX_SPI2_TXHOLD_REc (ARM_AUX_BASE + 0xf8)
#define ARM_AUX_SPI2_TXHOLD_REd (ARM_AUX_BASE + 0xfc)

#endif